/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controlador;

import Vista.*;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author juanpbaucl
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public mainFrame() {
        this.initComponents();
        this.iniciarContenido();
    }

    public void iniciarContenido(){
        this.contenido.setLayout(new BorderLayout());
        this.mostrarPanel(new Tanquear());
    }

    public void mostrarPanel(JPanel panel){
        panel.setSize(750, 430);
        panel.setLocation(0,0);

        this.contenido.removeAll();
        this.contenido.add(panel, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint(); 
     
    }
 

    public void setTanquear(JButton Tanquear) {
        this.Tanquear = Tanquear;
    }

    public JButton getTanquear() {
        return this.Tanquear;
    }

    public void setComprar_Productos(JButton Comprar_Productos) {
        this.Comprar_Productos = Comprar_Productos;
    }

    public JButton getComprar_Productos() {
        return this.Comprar_Productos;
    }

    public void setReporteDeVentas(JButton ReporteDeVentas) {
        this.ReporteDeVentas = ReporteDeVentas;
    }

    public JButton getReporteDeVentas() {
        return this.ReporteDeVentas;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.Background = new javax.swing.JPanel();
        this.Options = new javax.swing.JPanel();
        this.jLabel1 = new javax.swing.JLabel();
        this.Tanquear = new javax.swing.JButton();
        this.Comprar_Productos = new javax.swing.JButton();
        this.ReporteDeVentas = new javax.swing.JButton();
        this.GenerarFactura = new javax.swing.JButton();
        this.contenido = new javax.swing.JPanel();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        this.Background.setBackground(new java.awt.Color(255, 255, 255));

        this.Options.setBackground(new java.awt.Color(51, 51, 51));

        this.jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        this.jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        this.jLabel1.setText("   Gasolineria Gasosaurus");

        this.Tanquear.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        this.Tanquear.setText("Tanquear Vehiculo");
        this.Tanquear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        this.Tanquear.setBorderPainted(false);
        this.Tanquear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.Tanquear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        this.Tanquear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        this.Tanquear.setIconTextGap(30);
        this.Tanquear.setVerifyInputWhenFocusTarget(false);
        this.Tanquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrame.this.TanquearActionPerformed(evt);
            }
        });

        this.Comprar_Productos.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        this.Comprar_Productos.setText("Comprar Productos");
        this.Comprar_Productos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        this.Comprar_Productos.setBorderPainted(false);
        this.Comprar_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.Comprar_Productos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        this.Comprar_Productos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        this.Comprar_Productos.setIconTextGap(30);
        this.Comprar_Productos.setVerifyInputWhenFocusTarget(false);
        this.Comprar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrame.this.Comprar_ProductosActionPerformed(evt);
            }
        });

        this.ReporteDeVentas.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        this.ReporteDeVentas.setText("Reporte de Ventas");
        this.ReporteDeVentas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        this.ReporteDeVentas.setBorderPainted(false);
        this.ReporteDeVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.ReporteDeVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        this.ReporteDeVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        this.ReporteDeVentas.setIconTextGap(30);
        this.ReporteDeVentas.setVerifyInputWhenFocusTarget(false);
        this.ReporteDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrame.this.ReporteDeVentasActionPerformed(evt);
            }
        });

        this.GenerarFactura.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        this.GenerarFactura.setText("Generar Factura de Venta");
        this.GenerarFactura.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        this.GenerarFactura.setBorderPainted(false);
        this.GenerarFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        this.GenerarFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        this.GenerarFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        this.GenerarFactura.setIconTextGap(30);
        this.GenerarFactura.setVerifyInputWhenFocusTarget(false);
        this.GenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrame.this.GenerarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionsLayout = new javax.swing.GroupLayout(this.Options);
        this.Options.setLayout(OptionsLayout);
        OptionsLayout.setHorizontalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(this.jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
            .addComponent(this.Tanquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(this.Comprar_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(this.ReporteDeVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(this.GenerarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OptionsLayout.setVerticalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(this.jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(this.Tanquear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.Comprar_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.ReporteDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.GenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        this.contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(this.contenido);
        this.contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(this.Background);
        this.Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(this.Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(this.contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(this.Options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(this.contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(this.Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(this.Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanquearActionPerformed(java.awt.event.ActionEvent evt) {
        // Inicializacion del compoente de la ventana principal
        this.mostrarPanel(new Tanquear());
    }

    private void GenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {
        //Funcion para generar la factura de venta en formato PDF 

    }

    private void Comprar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {
       this.mostrarPanel(new Productos ());
    }
    private void ReporteDeVentasActionPerformed(java.awt.event.ActionEvent evt) {
        this.mostrarPanel(new Consolidado());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Comprar_Productos;
    private javax.swing.JButton GenerarFactura;
    private javax.swing.JPanel Options;
    private javax.swing.JButton ReporteDeVentas;
    private javax.swing.JButton Tanquear;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
