/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controlador;

/**
 *
 * @author juanpbaucl
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Options = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tanquear = new javax.swing.JButton();
        Comprar_Productos = new javax.swing.JButton();
        ReporteDeVentas = new javax.swing.JButton();
        GenerarFactura = new javax.swing.JButton();
        Modelo_Vista = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        Options.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Gasolineria Gasosaurus");

        Tanquear.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        Tanquear.setText("Tanquear Vehiculo");
        Tanquear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        Tanquear.setBorderPainted(false);
        Tanquear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tanquear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tanquear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Tanquear.setIconTextGap(30);
        Tanquear.setVerifyInputWhenFocusTarget(false);
        Tanquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanquearActionPerformed(evt);
            }
        });

        Comprar_Productos.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        Comprar_Productos.setText("Comprar Productos");
        Comprar_Productos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        Comprar_Productos.setBorderPainted(false);
        Comprar_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Comprar_Productos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Comprar_Productos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Comprar_Productos.setIconTextGap(30);
        Comprar_Productos.setVerifyInputWhenFocusTarget(false);
        Comprar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comprar_ProductosActionPerformed(evt);
            }
        });

        ReporteDeVentas.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        ReporteDeVentas.setText("Reporte de Ventas");
        ReporteDeVentas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        ReporteDeVentas.setBorderPainted(false);
        ReporteDeVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ReporteDeVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReporteDeVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ReporteDeVentas.setIconTextGap(30);
        ReporteDeVentas.setVerifyInputWhenFocusTarget(false);
        ReporteDeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDeVentasActionPerformed(evt);
            }
        });

        GenerarFactura.setFont(new java.awt.Font("URW Gothic", 0, 18)); // NOI18N
        GenerarFactura.setText("Generar Factura de Venta");
        GenerarFactura.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 30, 1, 1, new java.awt.Color(0, 0, 0)));
        GenerarFactura.setBorderPainted(false);
        GenerarFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GenerarFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GenerarFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        GenerarFactura.setIconTextGap(30);
        GenerarFactura.setVerifyInputWhenFocusTarget(false);
        GenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionsLayout = new javax.swing.GroupLayout(Options);
        Options.setLayout(OptionsLayout);
        OptionsLayout.setHorizontalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
            .addComponent(Tanquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Comprar_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ReporteDeVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GenerarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OptionsLayout.setVerticalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Tanquear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comprar_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReporteDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        Modelo_Vista.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Modelo_VistaLayout = new javax.swing.GroupLayout(Modelo_Vista);
        Modelo_Vista.setLayout(Modelo_VistaLayout);
        Modelo_VistaLayout.setHorizontalGroup(
            Modelo_VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        Modelo_VistaLayout.setVerticalGroup(
            Modelo_VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Modelo_Vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Modelo_Vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanquearActionPerformed
        // Inicializacion del compoente de la ventana principal
    }//GEN-LAST:event_TanquearActionPerformed

    private void GenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerarFacturaActionPerformed

    private void Comprar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comprar_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comprar_ProductosActionPerformed

    private void ReporteDeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDeVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteDeVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Comprar_Productos;
    private javax.swing.JButton GenerarFactura;
    private javax.swing.JPanel Modelo_Vista;
    private javax.swing.JPanel Options;
    private javax.swing.JButton ReporteDeVentas;
    private javax.swing.JButton Tanquear;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
