-- MySQL Script generated by MySQL Workbench
-- sáb 06 may 2023 20:13:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbGasolinera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbGasolinera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbGasolinera` ;
USE `dbGasolinera` ;

-- -----------------------------------------------------
-- Table `dbGasolinera`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbGasolinera`.`Empleados` (
  `idEmpleados` INT NOT NULL,
  `NombreEmpleado` VARCHAR(45) NULL,
  `ApellidoEmpleado` VARCHAR(45) NULL,
  `DirreccionEmpleado` VARCHAR(45) NULL,
  `TelefonoEmpleado` VARCHAR(45) NULL,
  `CorreoEmpleado` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbGasolinera`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbGasolinera`.`Clientes` (
  `idClientes` INT NOT NULL,
  `NombreC` VARCHAR(45) NULL,
  `ApellidoC` VARCHAR(45) NULL,
  `TelefonoC` VARCHAR(45) NULL,
  `CorreoC` VARCHAR(45) NULL,
  `DirreccionC` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbGasolinera`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbGasolinera`.`Factura` (
  `idFacturas` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `PrecioTotal` INT NULL,
  `CantidadTotal` INT(100) NULL,
  PRIMARY KEY (`idFacturas`, `Clientes_idClientes`),
  INDEX `fk_Facturas_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Facturas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `dbGasolinera`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbGasolinera`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbGasolinera`.`Ventas` (
  `idVentas` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  `FechaVenta` VARCHAR(45) NULL,
  `HoraVenta` VARCHAR(45) NULL,
  `Factura_idFacturas` INT NOT NULL,
  `Factura_Clientes_idClientes` INT NOT NULL,
  `CantidadVendida` INT(100) NULL,
  PRIMARY KEY (`idVentas`, `Empleados_idEmpleados`, `Factura_idFacturas`, `Factura_Clientes_idClientes`),
  INDEX `fk_Ventas_Empleados_idx` (`Empleados_idEmpleados` ASC) VISIBLE,
  INDEX `fk_Ventas_Factura1_idx` (`Factura_idFacturas` ASC, `Factura_Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Empleados`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `dbGasolinera`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Factura1`
    FOREIGN KEY (`Factura_idFacturas` , `Factura_Clientes_idClientes`)
    REFERENCES `dbGasolinera`.`Factura` (`idFacturas` , `Clientes_idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbGasolinera`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbGasolinera`.`Productos` (
  `idProductos` INT NOT NULL,
  `NombreProducto` VARCHAR(45) NULL,
  `PrecioProducto` INT NULL,
  `CantidadDisponible` INT NULL,
  `Ventas_idVentas` INT NOT NULL,
  `Ventas_Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `Ventas_idVentas`, `Ventas_Empleados_idEmpleados`),
  INDEX `fk_Productos_Ventas1_idx` (`Ventas_idVentas` ASC, `Ventas_Empleados_idEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Ventas1`
    FOREIGN KEY (`Ventas_idVentas` , `Ventas_Empleados_idEmpleados`)
    REFERENCES `dbGasolinera`.`Ventas` (`idVentas` , `Empleados_idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
